from vector import Vector

print("From int")
print(Vector(10))
print("From tuple")
print(Vector((5, 15)))
print("From list")
print(Vector([1,2,3,4,5,6,7]))

v = Vector((0, 10))
w = Vector((5, 15))

print("Vector + Scalar :")
print(v + 10)
print("Vector - Scalar :")
print(v - 10)
print("Vector * Scalar :")
print(v * 10)
print("Vector / Scalar :")
print(v / 10)
print("Scalar + Vector :")
print(10 + v)
print("Scalar - Vector :")
print(10 - v)
print("Scalar * Vector :")
print(10 * v)
print("Scalar / Vector :")
print(10 / v)
print("Vector + Vector :")
print(v + w)
print("Vector - Vector :")
print(v - w)
print("Vector * Vector :")
print(v * w)

